/** ###################################################################
**     THIS BEAN MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PORTCOUT.H
**     Project   : DC17
**     Processor : MC56F8006_32_LQFP
**     Beantype  : BitsIO
**     Version   : Bean 02.098, Driver 01.19, CPU db: 3.00.169
**     Compiler  : Metrowerks DSP C Compiler
**     Date/Time : 3/23/2009, 7:38 PM
**     Abstract  :
**         This bean "BitsIO" implements a multi-bit input/output.
**         It uses selected pins of one 1-bit to 8-bit port.
**         Note: This bean is set to work in Output direction only.
**     Settings  :
**         Port name                   : GPIOC
**
**         Bit mask of the port        : 7
**         Number of bits/pins         : 3
**         Single bit numbers          : 0 to 2
**         Values range                : 0 to 7
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : off
**
**         Port data register          : GPIO_C_DR [61889]
**         Port control register       : GPIO_C_DDR [61890]
**         Port function register      : GPIO_C_PER [61891]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    12   |   GPIOC0_ANA5_FAULT0_CMP1_M1
**                    1      |    11   |   GPIOC1_PGA0NON_INV_ANA7_CMP2_M2
**                    2      |    10   |   GPIOC2_PGA0INV_ANA9_CMP2_P4
**             ----------------------------------------------------
**
**         Optimization for            : code size
**     Contents  :
**         No public methods
**
**     (c) Copyright UNIS, a.s. 1997-2008
**     UNIS, a.s.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################*/

#ifndef __PORTCOUT_H
#define __PORTCOUT_H

/* MODULE PORTCOUT. */

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

#include "Cpu.h"

#define PORTCOUT_PIN_MASK       ((byte)7) /* Pin mask */


/*
** ===================================================================
**     Method      :  BitsIO__GetMsk (bean BitsIO)
**
**     Description :
**         Returns pin mask. The method is called automatically as a part 
**         of bit method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
word BitsIO__GetMsk(byte bitNum, byte bitFirst);

/* END PORTCOUT. */

#endif /* __PORTCOUT_H*/
/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.99 [04.17]
**     for the Freescale 56800 series of microcontrollers.
**
** ###################################################################
*/
